name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is needed for trusted publishing

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build package
      run: python -m build
    - name: Publish to TestPyPI (if tag contains 'test')
      if: contains(github.ref, 'test')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        # No password needed for Trusted Publishing
    - name: Publish to PyPI (if tag does not contain 'test')
      if: !contains(github.ref, 'test')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # No password needed for Trusted Publishing