name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Build and publish Python package
    runs-on: ubuntu-latest
    # Specifies that the job needs a write token to the id-token.
    # This is required for trusted publishing.
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: python -m pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Publish package to TestPyPI
        if: contains(github.ref_name, '-test')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          # Trusted publishing is used by default, no token needed.
          # You must configure TestPyPI to trust this workflow.

      - name: Publish package to PyPI
        if: "!contains(github.ref_name, '-test')"
        uses: pypa/gh-action-pypi-publish@release/v1
